name: Build Docker Images
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source
        run: |
          sudo apt install -y git && git clone -b main https://github.com/SagerNet/sing-box.git sing-box
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/skyxim/sing-box
      - name: Get tag to build
        id: tag
        working-directory: sing-box
        run: |
          if [[ -z "${{ github.event.inputs.tag }}" ]]; then
            echo ::set-output name=tag::ghcr.io/skyxim/sing-box:${{ github.ref_name }}
          else
            echo ::set-output name=tag::ghcr.io/skyxim/sing-box:${{ github.event.inputs.tag }}
          fi
      - name: Build and release Docker images
        uses: docker/build-push-action@v2
        with:
          context: ./sing-box
          platforms: linux/amd64,linux/arm64
          target: dist
          tags: ${{ steps.tag.outputs.tag }}
          push: true
